import manifest from "@/content/media-manifest.json";

/**
 * Intrinsic dimensions for every image under /public/media, generated by the
 * media pipeline. next/image needs width and height to reserve layout space
 * before the file loads, and hard-coding them per call site guarantees they
 * drift from the files.
 */
type Dimensions = { width: number; height: number };

const dimensions = manifest as Record<string, Dimensions>;

export function getDimensions(src: string): Dimensions | null {
  return dimensions[src] ?? null;
}

/** A sensible aspect-ratio string for a known image, for layout reservation. */
export function getAspect(src: string, fallback = "16 / 10"): string {
  const size = getDimensions(src);
  return size ? `${size.width} / ${size.height}` : fallback;
}
